### ISSUE TITLE
Error in rawToChar(data) : embedded nul in string:

### ISSUE THREAD

**Issue by shalutiwari** [rstudio/shinytest#189] opened 2018-04-13 18:36 UTC
Getting this error when you run below command second time.

```
testApp('016-knitr-pdf') 
Running mytest.R 
==== Comparing mytest... 
  Differences detected between mytest-current/ and mytest-expected/:

    Name            Status      
    001.json        No change   
    001.png         No change   
    002.json        No change   
    002.png         No change   
    003.json        No change   
    003.png         No change   
    004.json        No change   
    004.png         No change   
    005.json        No change   
    005.png         No change   
    006.json        No change   
    006.png         No change   
    007.json        No change   
    007.png         No change   
    008.json        No change   
    008.png         No change   
    009.download != Files differ
Would you like to view the differences between expected and current results [y/n]? y
Differences in current results found for: mytest
Viewing diff for mytest
Error in rawToChar(data) : 
  embedded nul in string: 'PK\003\004\024\0\002\b\b\0\xd4p\x8dL\xe1\001\xdb\rt\001\0\0i\006\0\0\023\0\0\0[Content_Types].xml\xb5\x95\xcbj\xc30\020E\xf7\xfd\n\xa3m\xb1\x95dQJ\x89\x93E\037\xd0M\033h\xfa\001\x8a4vD\xad\a\xd2\xe4\xf5\xf7\035ۍ)\xa1ġI6\006{f\xee=\xbe\x8c\xec\xf1tk\xaad\r!jgs6\xcc\006,\001+\x9dҶ\xcc\xd9\xe7\xfc%\xbdg\xd3\xc9\xcdx\xbe\xf3\020\023\xea\xb51gKD\xff\xc0y\x94K0"f\u0383\xa5J\xe1\x82\021H\xb7\xa1\xe4^\xc8/Q\002\037\r\006w\\:\x8b`1\xc5Z\x83M\xc6OP\x88U\x85\xc9\xf3\x96\036\xb7\xbe4ΒǶ\xaf\xb6ʙ\xf0\xbe\xd2R \x95yS\xe5\177\016\006\xa8\xe2\x91ɵU\ax\xe9\017ZF\x93MO\\j\037o\xf7\026\xef\024E\xd0\n\x92\x99\b\xf8&\f\xe9\xf1\x8d\v\x8ao`\xf1\001\x88\024K̎\xd3\xfe\xe1\xe9\x8aBKPN\xae\f\x8dd\xb5\xa0\017NB\x8c\xa4g\xaa\xec\x97x?\x89]\x99\005\004\xea\xbd<G'\xddO\021\xaf\026F<9\t\xa4\xfd\x83\xf6:<\x9b\xa3\x91\xe9\xf7,\xc8a.\026\025\\\xfe\xc5;\xe9\xa3\0244?\v\xceGNng3@}\x92\024\xa8\x94@<\004\xd4p<\xf6\xce\\\xba\xf0\x8f\004\xf6g\xaf\x9e>ղ\xdd6\xdcUp\x8d]kt\xfb\xfd;\x85\
```

mytest.R

```
app <- ShinyDriver$new("../", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(goButton = "click")
app$snapshot()
app$setInputs(n = 49)
app$setInputs(n = 50)
app$setInputs(n = 51)
app$setInputs(n = 52)
app$setInputs(n = 53)
app$setInputs(n = 54)
app$setInputs(n = 55)
app$setInputs(n = 56)
app$setInputs(n = 57)
app$setInputs(n = 58)
app$setInputs(n = 59)
app$setInputs(n = 60)
app$setInputs(n = 61)
app$setInputs(n = 62)
app$setInputs(n = 63)
app$setInputs(n = 64)
app$setInputs(n = 65)
app$setInputs(n = 66)
app$setInputs(n = 67)
app$setInputs(n = 68)
app$setInputs(n = 69)
app$setInputs(n = 70)
app$setInputs(n = 71)
app$setInputs(n = 72)
app$setInputs(n = 73)
app$setInputs(n = 74)
app$setInputs(n = 75)
app$setInputs(n = 76)
app$setInputs(n = 77)
app$setInputs(n = 78)
app$setInputs(n = 79)
app$setInputs(n = 80)
app$setInputs(n = 81)
app$snapshot()
app$setInputs(goButton = "click")
app$snapshot()
```

**Comment by hadley** [comment] 2020-08-12 12:52
Reprex:

```R
path <- "../shiny-examples/016-knitr-pdf"
dir.create(file.path(path, "tests", "shinytest"), recursive = TRUE)
writeLines(con = file.path(path, "tests", "shinytest", "mytest.R"), 
'app <- ShinyDriver$new("../../report.Rmd", shinyOptions = list(display.mode = "normal"))
app$snapshotInit("mytest")
app$snapshot()
')
shinytest::testApp(file.path(path, "report.Rmd"))
```

This now gives:

```
Running mytest.R Error: lexical error: invalid char in json text.
                                       <html>  <head>   <title>An erro
                     (right here) ------^
```

So this is a duplicate of #195

**Closed by hadley** 2020-08-12 12:52 UTC
