### ISSUE TITLE
Error in sd_startShiny error

### ISSUE THREAD

**Issue by kambanane** [rstudio/shinytest#230] opened 2018-12-17 20:38 UTC
I tried recordTest(getwd(), shinyOptions = list(port=8000)) and got the following error and output. I do not know where to begin.

Error in sd_startShiny(self, private, path, seed, loadTimeout, shinyOptions) : 
  Error starting application:
Running application in test mode.
Loading required package: shiny
Warning: package 'shiny' was built under R version 3.5.1
Warning: package 'shinydashboard' was built under R version 3.5.1

Attaching package: 'shinydashboard'

The following object is masked from 'package:graphics':

    box

Warning: package 'shinythemes' was built under R version 3.5.1
Warning: package 'shinyWidgets' was built under R version 3.5.1
Warning: package 'flexdashboard' was built under R version 3.5.1

Attaching package: 'flexdashboard'

The following objects are masked from 'package:shinydashboard':

    renderValueBox, valueBox, valueBoxOutput

Warning: package 'leaflet' was built under R version 3.5.1
Warning: package 'leaflet.extras' was built under R version 3.5.1
Warning: package 'DT' was built under R version 3.5.1

Attaching package: 'DT'

The following objects are masked from 'package:shiny':

    dataTableOutput, renderDataTable

Warning: package 'htmltools' w

**Comment by davidruegamer** [comment] 2019-02-13 09:06
I ran into the same / similar problem today. Regarding the non-informative error message it seems that only the first line of the log file which is supposed to be printed as error in  https://github.com/rstudio/shinytest/blob/dfc163ca29070bfc6aefb35a6e18d97517c4676b/R/initialize.R#L131 is actually printed in the console. My log file looks as follows

```
Running application in test mode.
Loading required package: shiny
-- [1mAttaching packages[22m -------------------------------------------------------- tidyverse 1.2.1 --
[32mv[39m [34mggplot2[39m 3.1.0     [32mv[39m [34mpurrr  [39m 0.2.5
[32mv[39m [34mtibble [39m 1.4.2     [32mv[39m [34mdplyr  [39m 0.7.8
[32mv[39m [34mtidyr  [39m 0.8.2     [32mv[39m [34mstringr[39m 1.3.1
[32mv[39m [34mreadr  [39m 1.3.1     [32mv[39m [34mforcats[39m 0.3.0
-- [1mConflicts[22m ----------------------------------------------------------- tidyverse_conflicts() --
[31mx[39m [34mdplyr[39m::[32mfilter()[39m masks [34mstats[39m::filter()
[31mx[39m [34mdplyr[39m::[32mlag()[39m    masks [34mstats[39m::lag()

Attaching package: 'data.table'

The following objects are masked from 'package:dplyr':

    between, first, last

The following object is masked from 'package:purrr':

    transpose

Loading required package: viridisLite

Attaching package: 'plotly'

The following object is masked from 'package:ggplot2':

    last_plot

The following object is masked from 'package:stats':

    filter

The following object is masked from 'package:graphics':

    layout

Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3

Attaching package: 'shinyjs'

The following object is masked from 'package:shiny':

    runExample

The following objects are masked from 'package:methods':

    removeClass, show


Attaching package: 'lubridate'

The following objects are masked from 'package:data.table':

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year

The following object is masked from 'package:base':

    date

Error : RStudio not running
```

**Comment by davidruegamer** [comment] 2019-02-13 09:59
PS: In my special case the actual error was caused by `shiny:::sourceUTF8`, which evaluates my `global.R` script including the line
```
wd <- dirname(rstudioapi::getSourceEditorContext()$path)
```
Although this line works when running shiny itself, in this case `rstudioapi::getSourceEditorContext()` returns `NULL`. 
Not sure if this helps...

**Comment by hadley** [comment] 2020-08-07 19:58
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2020-08-07 19:58 UTC
