### ISSUE TITLE
Should not error out when app fails to start properly

### ISSUE THREAD

**Issue by wch** [rstudio/shinytest#122] opened 2017-08-23 16:43 UTC
If an application fails to start, the `$new()` should not error out, and should return an object, so that it can be inspected to diagnose the problem.

Perhaps it should work like this:
* By default, if there's a startup error, print the logs, save a screenshot, and throw an error.
* Add an option that allows it to continue running and return a valid ShinyDriver object for inspection.

This way, the default behavior will still be usefule for automated testing.

**Comment by hadley** [comment] 2020-08-08 13:32
Duplicate of #329

**Closed by hadley** 2020-08-08 13:32 UTC
