### ISSUE TITLE
Make sure Shiny modules work

### ISSUE THREAD

**Issue by gaborcsardi** [rstudio/shinytest#3] opened 2016-08-28 06:30 UTC

**Comment by Avatoo** [comment] 2017-02-09 14:56
Hi @gaborcsardi,

Can modules be tested at the moment? 

I tried the [module example ](http://shiny.rstudio.com/gallery/module-example.html). It runs ok when no interaction. Only it tells me the screenshot is different. My eyes are not able to capture the change. When some points are specified on the left, the test reports error. The testing result would be like the below. Is it because modules cannot be tested properly or some cases are abnormal? Any clues?

====== Running mytests_wo_action.R ======
  Differences detected between mytests-current/ and mytests-expected/:

    Name         Status      
    001.json     No change   
    001.png   != Files differ

  To save current results as expected results, run:
    snapshotUpdate("mytests_wo_action", "108-module-output")

====== Running mytests_action.R ======
Error in session_makeRequest(self, private, endpoint, data, params, headers) : 
  Unable to find input binding for element with id scatters-brush

Thanks a lot,
Ava

**Comment by gaborcsardi** [comment] 2017-02-09 14:59
I don't know, maybe @wch does.

**Comment by ndimhypervol** [comment] 2017-07-11 15:33
Hello. Any updates on this? I can't reproduce this error, but I'd like to know that shinytest works well with modules. Thanks!

**Comment by hadley** [comment] 2020-08-08 13:45
I don't think there's any evidence that shinytest doesn't work with modules, so I'm going to close this issue. If you have specific issues, please file a new issue 😄

**Closed by hadley** 2020-08-08 13:45 UTC
