### ISSUE TITLE
snapshotCompare doesn't work when several files provided

### ISSUE THREAD

**Issue by KZARCA** [rstudio/shinytest#228] opened 2018-11-21 11:47 UTC
`snapshotCompare()` works as expected when provided only one test. 
```r
snapshotCompare(appdir, testnames = test1.R, interactive = TRUE)
```
However, when  several tests are provided, only one test out of two are displayed in the browser.
```r
snapshotCompare(appdir, interactive = TRUE)
```

I tried:
``` r
testnames <- c("test1.R", "test2.R", "test3.R")
appdir <- system.file("shiny", package = "mypackage")
all_files <- dir(file.path(appdir, "tests"))
lapply(testnames, function(x){
  snapshotCompare(appdir, testnames = x), interactive = TRUE)
})
```
<sup>Created on 2018-11-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

but I got the same issue. I tried to modify the order of testnames, and that inverts the tests correctly displayed on the browser. 
I also checked  `viewTestDiff()` and the issue exists there as well.

I tried with the tests included into the shinytest package, and got the same problem:

```r
  app_dirs <- Filter(dir.exists, dir("tests/testthat/recorded_tests", full.names = TRUE))
  if (length(app_dirs) > 0) {
    for (app_dir in app_dirs) {
      # If the dir contains an .Rmd, add that to the path
      shinytest::testApp(app_dir, compareImages = FALSE)
    }
  }
```

<details>
My R session
```
─ Session info ───────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Ubuntu 18.04.1 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  fr_FR.UTF-8                 
 ctype    fr_FR.UTF-8                 
 tz       Europe/Paris                
 date     2018-11-26                  

─ Packages ───────────────────────────────────────────────────────────────────────────────
 ! package     * version    date       lib source                            
   assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.1)                    
   backports     1.1.2      2017-12-13 [1] CRAN (R 3.5.1)                    
   base64enc     0.1-3      2015-07-28 [1] CRAN (R 3.5.1)                    
   callr         3.0.0      2018-08-24 [1] CRAN (R 3.5.1)                    
   cli           1.0.1      2018-09-25 [1] CRAN (R 3.5.1)                    
   crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.1)                    
   curl          3.2        2018-03-28 [1] CRAN (R 3.5.1)                    
   debugme       1.1.0      2017-10-22 [1] CRAN (R 3.5.1)                    
   desc          1.2.0      2018-05-01 [1] CRAN (R 3.5.1)                    
   devtools      2.0.1      2018-10-26 [1] CRAN (R 3.5.1)                    
   digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.1)                    
   fs            1.2.6      2018-08-23 [1] CRAN (R 3.5.1)                    
   glue          1.3.0      2018-07-17 [1] CRAN (R 3.5.1)                    
   htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.5.1)                    
   htmlwidgets   1.3        2018-09-30 [1] CRAN (R 3.5.1)                    
   httpuv        1.4.5      2018-07-19 [1] CRAN (R 3.5.1)                    
   httr          1.3.1      2017-08-20 [1] CRAN (R 3.5.1)                    
   jsonlite      1.5        2017-06-01 [1] CRAN (R 3.5.1)                    
   later         0.7.5      2018-09-18 [1] CRAN (R 3.5.1)                    
   magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.1)                    
   memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.1)                    
   mime          0.6        2018-10-05 [1] CRAN (R 3.5.1)                    
   parsedate     1.1.3      2017-03-02 [1] CRAN (R 3.5.1)                    
   pingr         1.1.2      2017-03-02 [1] CRAN (R 3.5.1)                    
   pkgbuild      1.0.2      2018-10-16 [1] CRAN (R 3.5.1)                    
   pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.5.1)                    
   png           0.1-7      2013-12-03 [1] CRAN (R 3.5.1)                    
   prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.1)                    
   processx      3.2.0      2018-08-16 [1] CRAN (R 3.5.1)                    
   promises      1.0.1      2018-04-13 [1] CRAN (R 3.5.1)                    
   ps            1.2.1      2018-11-06 [1] CRAN (R 3.5.1)                    
   R6            2.3.0      2018-10-04 [1] CRAN (R 3.5.1)                    
   Rcpp          1.0.0      2018-11-07 [1] CRAN (R 3.5.1)                    
   rematch       1.0.1      2016-04-21 [1] CRAN (R 3.5.1)                    
   remotes       2.0.2      2018-10-30 [1] CRAN (R 3.5.1)                    
   rlang         0.3.0.1    2018-10-25 [1] CRAN (R 3.5.1)                    
   rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.1)                    
   rstudioapi    0.8        2018-10-02 [1] CRAN (R 3.5.1)                    
   sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.5.1)                    
   shiny       * 1.2.0      2018-11-02 [1] CRAN (R 3.5.1)                    
 P shinytest   * 1.3.0.9000 2018-11-23 [?] Github (rstudio/shinytest@a88681b)
   showimage     1.0.0      2018-01-24 [1] CRAN (R 3.5.1)                    
   testthat    * 2.0.1      2018-10-13 [1] CRAN (R 3.5.1)                    
   usethis       1.4.0      2018-08-14 [1] CRAN (R 3.5.1)                    
   webdriver     1.0.5      2018-04-11 [1] CRAN (R 3.5.1)                    
   withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.1)                    
   xtable        1.8-3      2018-08-29 [1] CRAN (R 3.5.1)                    

[1] /home/kevin/R/x86_64-pc-linux-gnu-library/3.5
[2] /usr/local/lib/R/site-library
[3] /usr/lib/R/site-library
[4] /usr/lib/R/library
```
</details>

**Comment by hadley** [comment] 2020-08-07 19:59
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2020-08-19 22:43
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2020-08-19 22:43 UTC
Labels: reprex
