### ISSUE TITLE
Should decide best practices for saving images

### ISSUE THREAD

**Issue by wch** [rstudio/shinytest#126] opened 2017-08-25 02:33 UTC
For example, in a package, we don't want to save the PNGs as part of the repo because they can really bloat the package and repo size. But the PNGs are still useful to see what the app originally looked like. The same issue crops up in app repositories that aren't R packages.

**Comment by hadley** [comment] 2020-08-08 13:31
Duplicate of #140

**Closed by hadley** 2020-08-08 13:31 UTC
