### ISSUE TITLE
Screenshot of selected CSS element

### ISSUE THREAD

**Issue by rpodcast** [rstudio/shinytest#187] opened 2018-04-12 15:33 UTC
I've been using the [`webshot`](https://github.com/wch/webshot) package for some side projects and the capability of taking a screenshot of a particular element with CSS selectors (i.e. with `webshot("https://www.r-project.org/", "r-sidebar.png", selector = ".sidebar")` is really nice. Is it possible to extend this feature to `app$takeScreenshot()`?

**Comment by thercast** [comment] 2018-06-12 16:57
I've done some investigation on ways to integrate this feature, but I'm not sure the optimal approach.  In case it helps here's what I've found:
* `shinytest` currently relies on [`webdriver`](https://github.com/rstudio/webdriver) to create screenshots via the `takeScreenshot()` method.  Long ago it looks like there was some work to implement a element selection parameter for the screenshot method in `webdriver` per [rstudio/webdriver#13](https://github.com/rstudio/webdriver/issues/13), but the implementation did not perform as expected.
* If there was a way to invoke`webshot()` on the __already running__ phantomjs session serving the shiny app, then it seems like that could be a solution.  Of course I have no idea how difficult it would be to accomplish this.

**Comment by hadley** [comment] 2020-08-08 13:55
Duplicate of #260. We should have an implementation of this in the near future.

**Closed by hadley** 2020-08-08 13:55 UTC

**Comment by stla** [comment] 2021-09-22 06:42
Hello,

  This near future has coming now ? I would like to take a snapshot of a plot.
