### ISSUE TITLE
setInputs() in version 1.3.0.9001

### ISSUE THREAD

**Issue by emanko** [rstudio/shinytest#251] opened 2019-02-27 15:21 UTC
Recent changes in shinytest package (1.3.0.9001) include features of interest for me, as testing widgets that lack the direct input binding such as plotly or DT widgets). 

For simplification, to compare stable (1.3.0) and newest version I gave it a go with the snapshot tool and performed the same set of actions on the selected app. The test application I have selected contains two simple `selectInputs`, `renderPlotly` and `dataTableOutput`, so I will be able to test the newest feature. As expected snapshot tool recorded properly the values in the test script and _.json_ files for previously not seen objects with the argument `allowInputNoBinding_ = TRUE` - which is exciting.

**Generated test script**
```r
app <- ShinyDriver$new("../")
app$snapshotInit("test-inputs")

## Whole app
app$setInputs(`.clientValue-plotly_click-barplot` = "null", allowInputNoBinding_ = TRUE)
app$snapshot()

## After choosing assay - X
app$setInputs(assay = "X")
app$snapshot()
## After clicking last barplot for A
app$setInputs(`.clientValue-plotly_hover-barplot` = "[{\"curveNumber\":5,\"pointNumber\":0,\"x\":\"A\",\"y\":8}]", allowInputNoBinding_ = TRUE)
app$setInputs(`.clientValue-plotly_click-barplot` = "[{\"curveNumber\":5,\"pointNumber\":0,\"x\":\"A\",\"y\":8}]", allowInputNoBinding_ = TRUE)
app$setInputs(list_table_rows_current = c(1, 2, 3, 4, 5, 6, 7, 8), allowInputNoBinding_ = TRUE)
app$setInputs(list_table_rows_all = c(1, 2, 3, 4, 5, 6, 7, 8), allowInputNoBinding_ = TRUE)
app$setInputs(`.clientValue-plotly_hover-barplot` = character(0), allowInputNoBinding_ = TRUE)
app$snapshot()`
```

However, when I tried to incorporate the functionality without snapshot tool and instead with custom scripts I encountered not expected outcome. Using  `setInputs()`, similarly as stated above, did not behave as expected in the newest version. By checking the value of modified input with `getValue()` it turned out that instead of expected value, it was changed to empty string. Identical operation done in version 1.3.0 gives expected value - `"X"`.

```r
app <- ShinyDriver$new("../")
app$setInputs(assay = "X")
app$getValue("assay")
[1] ""
```

The question is whether this behaviour is easy to explain and expected? It would be highly appreciated if you could point me in the right direction with this, as the new features look very promising for me.

**Comment by hadley** [comment] 2020-08-07 19:51
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2020-08-27 22:23
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2020-08-27 22:23 UTC
Labels: reprex
