### ISSUE TITLE
Double click feature

### ISSUE THREAD

**Issue by goreaditya** [rstudio/shinytest#129] opened 2017-09-07 04:11 UTC
I was wondering if the double click functionality in either the driver or the web element is present. So far, I could only find `click()`.

**Comment by wch** [comment] 2017-09-07 16:12
There is only a `$click()` method for elements. Phantomjs does support double click, but it's currently not exposed by the webdriver package because it's not a standard part of the Webdriver protocol.

Does it work for you to just call `$click()` twice in a row?

**Comment by goreaditya** [comment] 2017-09-07 16:19
Unfortunately calling `$click()` twice in a row does not work.

**Comment by hadley** [comment] 2020-08-08 13:23
I'm going to close this issue because it's over three year olds, is relatively challenging to fix (since it requires cross-package work), and seems to affect relatively few people. It's our policy to close such issues to help stay focussed on the biggest problems, but the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.

**Closed by hadley** 2020-08-08 13:23 UTC

**Comment by CharlesBordet** [comment] 2022-08-09 13:20
Just wanted to chime in to mention that 

1) I have this need of double clicking as well, specifically in the context of editing a datatable cell.
2) I found a workaround with a short Javascript line that transforms simple clicks in double clicks.

Here is the code to transform clicks in double clicks for my datatable (id is `table`):

```
$('#table tbody tr td').click(function() {
    $(this).dblclick();
})
```

I run the Javascript code with `shinyjs::runjs()` function after the table is generated.
