### ISSUE TITLE
Use phantomJS::onLoadFinished() to detect when page is fully rendered ...

### ISSUE THREAD

**Issue by warnes** [rstudio/shinytest#358] opened 2020-08-26 22:59 UTC
Ideally, onLoadFinished would toggle the value of a status variable accessible that could be queried and waited on.  Then, perhaps, we could have `app$waitForLoadFinished()` and `app$getLoadFinished()` calls.

**Comment by warnes** [comment] 2020-08-26 23:16
Also see https://github.com/jonnnnyw/php-phantomjs/issues/85

**Comment by hadley** [comment] 2020-08-27 21:33
Is this a duplicate of #349?

**Comment by warnes** [comment] 2021-02-14 02:40
@hadley I think it targets a similar issue, but suggests a different approach.

**Comment by hadley** [comment] 2021-02-14 14:42
In that case I'll close and this issue will be linked in the discussion.

**Closed by hadley** 2021-02-14 14:42 UTC
