### ISSUE TITLE
RecordTest() does not record events

### ISSUE THREAD

**Issue by christoph-nepa** [rstudio/shinytest#236] opened 2019-01-14 13:37 UTC
I am working on two Shiny apps. One works with Shinytests as expected, but the other does not record any events. Instead it produces constantly the error message below. The strange thing is that both apps evolved from the same base, so they should not differ that much. Any idea what could cause the problem?

```
inject-recorder.js:56 Checking if frame is ready

VM5183:2 Uncaught TypeError: parent.postMessage is not a function
    at eval (eval at <anonymous> (shiny-testmode.js:7), <anonymous>:2:8)
    at shiny-testmode.js:7
```

**Comment by cpsievert** [comment] 2019-01-30 16:26
Are you embedding an iframe in the app that doesn't work? A reproducible example would be greatly appreciated.

**Comment by hadley** [comment] 2020-08-07 19:56
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2020-08-07 19:56 UTC
